#
# MySQL5.6
#

- name: install mysql
  yum: name={{ mysql_url }}/{{ item.rpm }} state=present
  with_items: mysql_items

- name: Install MySQL-python
  yum: name=MySQL-python

- name: start mysql
  service: name=mysql state=restarted enabled=yes

- name: get mysql password
  shell: cat /root/.mysql_secret | awk '{print $18}'
  register: mysql_root_password

- name: copy .my.cnf
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: setup mysql root
  command: mysqladmin -u root password {{ mysql_root_password.stdout }}

- name: add MySQL user
  mysql_user: name={{ mysql_user_name }} password={{ mysql_user_password }} priv=*.*:ALL,GRANT state=present

