- hosts: vagrants
  sudo: yes
  vars:
    rbenv:
      env: system
      version: v0.4.0
      ruby_version: 2.0.0-p353

  roles:
    - zsh
    - yumrepos
    - iptables
    - httpd
    - php
    - mysql
    - phpmyadmin
    - role: zzet.rbenv
      rbenv_users:
        - vagrant
    - bundler
    - passenger

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
